// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: tomato.proto

package tomato_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tomato struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tomato) Reset() {
	*x = Tomato{}
	mi := &file_tomato_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tomato) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tomato) ProtoMessage() {}

func (x *Tomato) ProtoReflect() protoreflect.Message {
	mi := &file_tomato_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tomato.ProtoReflect.Descriptor instead.
func (*Tomato) Descriptor() ([]byte, []int) {
	return file_tomato_proto_rawDescGZIP(), []int{0}
}

func (x *Tomato) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Ketchup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tomato        *Tomato                `protobuf:"bytes,1,opt,name=tomato,proto3" json:"tomato,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ketchup) Reset() {
	*x = Ketchup{}
	mi := &file_tomato_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ketchup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ketchup) ProtoMessage() {}

func (x *Ketchup) ProtoReflect() protoreflect.Message {
	mi := &file_tomato_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ketchup.ProtoReflect.Descriptor instead.
func (*Ketchup) Descriptor() ([]byte, []int) {
	return file_tomato_proto_rawDescGZIP(), []int{1}
}

func (x *Ketchup) GetTomato() *Tomato {
	if x != nil {
		return x.Tomato
	}
	return nil
}

var File_tomato_proto protoreflect.FileDescriptor

const file_tomato_proto_rawDesc = "" +
	"\n" +
	"\ftomato.proto\x12\ttomato.v1\"\"\n" +
	"\x06Tomato\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"4\n" +
	"\aKetchup\x12)\n" +
	"\x06tomato\x18\x01 \x01(\v2\x11.tomato.v1.TomatoR\x06tomato2A\n" +
	"\rTomatoService\x120\n" +
	"\aPrepare\x12\x11.tomato.v1.Tomato\x1a\x12.tomato.v1.KetchupB%Z#github.com/julian-siebert/tomato-gob\x06proto3"

var (
	file_tomato_proto_rawDescOnce sync.Once
	file_tomato_proto_rawDescData []byte
)

func file_tomato_proto_rawDescGZIP() []byte {
	file_tomato_proto_rawDescOnce.Do(func() {
		file_tomato_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tomato_proto_rawDesc), len(file_tomato_proto_rawDesc)))
	})
	return file_tomato_proto_rawDescData
}

var file_tomato_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tomato_proto_goTypes = []any{
	(*Tomato)(nil),  // 0: tomato.v1.Tomato
	(*Ketchup)(nil), // 1: tomato.v1.Ketchup
}
var file_tomato_proto_depIdxs = []int32{
	0, // 0: tomato.v1.Ketchup.tomato:type_name -> tomato.v1.Tomato
	0, // 1: tomato.v1.TomatoService.Prepare:input_type -> tomato.v1.Tomato
	1, // 2: tomato.v1.TomatoService.Prepare:output_type -> tomato.v1.Ketchup
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tomato_proto_init() }
func file_tomato_proto_init() {
	if File_tomato_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tomato_proto_rawDesc), len(file_tomato_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tomato_proto_goTypes,
		DependencyIndexes: file_tomato_proto_depIdxs,
		MessageInfos:      file_tomato_proto_msgTypes,
	}.Build()
	File_tomato_proto = out.File
	file_tomato_proto_goTypes = nil
	file_tomato_proto_depIdxs = nil
}
