// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: tomato.proto

package tomato_go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TomatoService_Prepare_FullMethodName = "/tomato.v1.TomatoService/Prepare"
)

// TomatoServiceClient is the client API for TomatoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TomatoServiceClient interface {
	Prepare(ctx context.Context, in *Tomato, opts ...grpc.CallOption) (*Ketchup, error)
}

type tomatoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTomatoServiceClient(cc grpc.ClientConnInterface) TomatoServiceClient {
	return &tomatoServiceClient{cc}
}

func (c *tomatoServiceClient) Prepare(ctx context.Context, in *Tomato, opts ...grpc.CallOption) (*Ketchup, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ketchup)
	err := c.cc.Invoke(ctx, TomatoService_Prepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TomatoServiceServer is the server API for TomatoService service.
// All implementations must embed UnimplementedTomatoServiceServer
// for forward compatibility.
type TomatoServiceServer interface {
	Prepare(context.Context, *Tomato) (*Ketchup, error)
	mustEmbedUnimplementedTomatoServiceServer()
}

// UnimplementedTomatoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTomatoServiceServer struct{}

func (UnimplementedTomatoServiceServer) Prepare(context.Context, *Tomato) (*Ketchup, error) {
	return nil, status.Error(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedTomatoServiceServer) mustEmbedUnimplementedTomatoServiceServer() {}
func (UnimplementedTomatoServiceServer) testEmbeddedByValue()                       {}

// UnsafeTomatoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TomatoServiceServer will
// result in compilation errors.
type UnsafeTomatoServiceServer interface {
	mustEmbedUnimplementedTomatoServiceServer()
}

func RegisterTomatoServiceServer(s grpc.ServiceRegistrar, srv TomatoServiceServer) {
	// If the following call panics, it indicates UnimplementedTomatoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TomatoService_ServiceDesc, srv)
}

func _TomatoService_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tomato)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TomatoServiceServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TomatoService_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TomatoServiceServer).Prepare(ctx, req.(*Tomato))
	}
	return interceptor(ctx, in, info, handler)
}

// TomatoService_ServiceDesc is the grpc.ServiceDesc for TomatoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TomatoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tomato.v1.TomatoService",
	HandlerType: (*TomatoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _TomatoService_Prepare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tomato.proto",
}
